-- Generated by nwg-displays on 2026-05-29 at 05:44:17. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@164.83",
    position = "1050x0",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1680x1050@59.88",
    position = "0x0",
    scale = 1.0,
    transform = 3
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.0",
    position = "3610x0",
    scale = 1.0,
    bitdepth = 10
})
